apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: parsl-role-binding
  namespace: pw-qa-test
subjects:
  - kind: ServiceAccount
    name: parsl-service-account
    namespace: pw-qa-test
roleRef:
  kind: Role
  name: parsl-role
  apiGroup: rbac.authorization.k8s.io
